name: MeasuringTape
version: 0.8b
author: DiddiZ
website: http://diddiz.insane-architects.net/
main: de.diddiz.MeasuringTape.MeasuringTape
description: Channels a string into a measuring tape.
commands:
  mt:
    description: 'MeasuringTape commands.'
    usage: 'Usage: /<command> help'
    aliases: []