name: MeasuringTape
version: 0.9
author: DiddiZ
website: http://diddiz.insane-architects.net/
main: de.diddiz.MeasuringTape.MeasuringTape
description: Channels a string into a measuring tape.
commands:
  mt:
    description: 'MeasuringTape commands.'
    usage: 'Usage: /<command> help'
    aliases: []
permissions:
  measuringtape.*:
    description: Gives access to all MeasuringTape commands
    children:
      measuringtape.tape: true
      measuringtape: true
      measuringtape: true
  measuringtape.tape:
    default: true
  measuringtape.tp:
    default: op
  measuringtape.measure:
    default: true